sonar.projectKey=ISCOUTB_AS_202620_Recobra
sonar.organization=isco-utb

# El source set debug no se entrega en release; no debe afectar el Quality Gate.
sonar.exclusions=**/android/**/src/debug/**,**/android/**/src/profile/**,**/build/**,**/.dart_tool/**

sonar.sources=.
sonar.sourceEncoding=UTF-8
